"""Resolve offline backtest pairs from the active V19.1 compatibility view.

The file is generated by ``ShariaFilter.sync_legacy_compat`` only after the
authoritative signed/report-bound V19.1 status has been accepted.  This helper
does not make a Sharia decision and cannot add a symbol.  It validates the
generated view strictly and fails closed when it is missing, malformed or
empty.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

DEFAULT_STABLECOINS = 'USDC,FDUSD,TUSD,USDP,DAI,EUR,AEUR,BUSD'
EXCLUDED_BASES = frozenset({'BTC', 'BNB'})
LEVERAGED_SUFFIXES = ('UP', 'DOWN', 'BULL', 'BEAR')
SYMBOL_RE = re.compile(r'^[A-Z0-9]{1,16}USDT$')


class BacktestPairError(ValueError):
    """The generated V19.1 compatibility view is not safe to consume."""


def _stablecoins() -> frozenset[str]:
    return frozenset(
        item.strip().upper()
        for item in os.getenv('STABLECOINS', DEFAULT_STABLECOINS).split(',')
        if item.strip()
    )


def load_pairs(path: str | Path) -> list[str]:
    source = Path(path)
    try:
        payload = json.loads(source.read_text(encoding='utf-8'))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise BacktestPairError(
            f'cannot read generated Sharia compatibility view {source}: {exc}') from exc
    if not isinstance(payload, dict):
        raise BacktestPairError('generated Sharia compatibility view must be an object')
    symbols = payload.get('symbols')
    if not isinstance(symbols, list):
        raise BacktestPairError(
            'generated Sharia compatibility view requires a symbols array')
    if not symbols:
        raise BacktestPairError(
            'no current V19.1 GREEN/GREEN_AVOID_OPTIONAL symbols are available')

    stablecoins = _stablecoins()
    pairs: list[str] = []
    seen: set[str] = set()
    for index, symbol in enumerate(symbols):
        if not isinstance(symbol, str) or not SYMBOL_RE.fullmatch(symbol):
            raise BacktestPairError(
                f'symbols[{index}] is not an exact uppercase Spot/USDT symbol')
        if symbol in seen:
            raise BacktestPairError(f'duplicate generated Sharia symbol: {symbol}')
        seen.add(symbol)
        base = symbol[:-4]
        if (base in EXCLUDED_BASES or base in stablecoins
                or any(base.endswith(suffix) for suffix in LEVERAGED_SUFFIXES)):
            raise BacktestPairError(
                f'generated Sharia symbol violates universe policy: {symbol}')
        pairs.append(f'{base}/USDT')
    return sorted(pairs)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        '--compat-file',
        default='../shared/sharia/halal_coins.json',
        help='screener-generated V19.1 compatibility view',
    )
    args = parser.parse_args(argv)
    try:
        pairs = load_pairs(args.compat_file)
    except BacktestPairError as exc:
        parser.exit(2, f'BACKTEST PAIR GATE BLOCKED: {exc}\n')
    for pair in pairs:
        print(pair)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
