from __future__ import annotations
"""Result persistence and status projection for the V19.1 screener.

The sharia-screener service is the ONLY writer of the canonical Sharia
directory. For every completed (or fail-closed) screening this module:

  1. writes the full V19.1 report to shared/sharia/reports/;
  2. writes an HMAC-authenticated result envelope carrying an Ed25519
     screener attestation to shared/sharia/results/; consumers require both;
  3. updates the sharia_status.json projection (schema_version 2, bound to
     the immutable controller hash) that gates the universe scanner, the
     Freqtrade strategy and the sidecar's cached check;
  4. regenerates the preserved core's halal_coins.json compatibility view
     (GREEN/GREEN_AVOID_OPTIONAL only);
  5. applies bounded retention to reports/results.

Verdict names are V19.1 final codes verbatim — never renamed.
"""
import hashlib
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

from services.common import envelope
from services.common.sharia_attestation import RESULT_PURPOSE, STATUS_PURPOSE, attach
from services.common.atomic import atomic_write_json
from services.common.audit import audit
from services.common.config_bounds import env_int
from services.common.paths import (
    LEGACY_HALAL_FILE, SHARIA_CONTROLLER_FILE, SHARIA_FILE, SHARIA_REPORTS_DIR,
    SHARIA_RESULTS_DIR,
)
from services.common.sharia_v19 import (
    TRADE_ELIGIBLE_CODES, V19_CONTROLLER_SHA256, V19_MAIN_FRAMEWORK,
    fail_closed_report, load_controller, validate_result,
)
from services.universe_service.sharia_filter import ShariaFilter

PRODUCER = 'sharia-screener'
REQUEST_ID_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')


def _now() -> datetime:
    return datetime.now(timezone.utc)


def status_skeleton() -> dict:
    return {
        '_comment': ('V19.1 execution-gate projection generated by the sharia-screener '
                     'service. Research screening only - not a fatwa.'),
        'schema_version': 2,
        'controller_sha256': V19_CONTROLLER_SHA256,
        'controller_version': V19_MAIN_FRAMEWORK,
        'generated_at': _now().isoformat(),
        'records': [],
    }


def _record_expiry(report: dict, *, validated: bool, completed_at: datetime) -> str:
    if not validated:
        retry = env_int('SHARIA_FAILED_RETRY_SECONDS', 21_600, 300, 7 * 86_400)
        return (completed_at + timedelta(seconds=retry)).isoformat()
    ttl_days = env_int('SHARIA_RESULT_TTL_DAYS', 30, 1, 365)
    hard_cap = completed_at + timedelta(days=ttl_days)
    try:
        rescreen = datetime.strptime(str(report.get('next_rescreen_date', '')), '%Y-%m-%d')
        rescreen = rescreen.replace(hour=23, minute=59, second=59, tzinfo=timezone.utc)
        return min(rescreen, hard_cap).isoformat()
    except Exception:
        return hard_cap.isoformat()


def update_status_projection(base: str, report: dict, *, request_id: str,
                             pair: str, validated: bool, report_file: str,
                             report_sha256: str, completed_at: datetime) -> dict:
    """Merge only independently validated and attested screening outcomes."""
    base = base.upper()
    load_controller(SHARIA_CONTROLLER_FILE)
    validate_result(report, expected_base=base)
    final_code = str(report['final_code'])
    if not validated and final_code in TRADE_ELIGIBLE_CODES:
        raise ValueError('unvalidated trade-eligible report cannot be projected')

    try:
        records = ShariaFilter(SHARIA_FILE).verified_projection_records()
    except Exception:
        # Plaintext/corrupt rows are dropped, never laundered by a new header.
        records = []
    record = attach({
        'symbol': base,
        'pair': pair,
        'status': final_code,
        'final_code': final_code,
        'validated': bool(validated),
        'reviewed_at': completed_at.date().isoformat(),
        'completed_at': completed_at.isoformat(),
        'expires_at': _record_expiry(report, validated=validated,
                                     completed_at=completed_at),
        'source': 'sharia-screener/v19.1',
        'controller_sha256': V19_CONTROLLER_SHA256,
        'confidence': str(report.get('confidence_level', 'LOW')),
        'human_escalation_required': bool(report.get('human_escalation_required', False)),
        'request_id': request_id,
        'report_file': report_file,
        'report_sha256': report_sha256,
    }, purpose=STATUS_PURPOSE)
    records = [r for r in records if str(r.get('symbol', '')).upper() != base]
    records.append(record)
    records.sort(key=lambda r: str(r.get('symbol', '')))
    current = status_skeleton()
    current['generated_at'] = completed_at.isoformat()
    current['records'] = records
    atomic_write_json(SHARIA_FILE, current)
    try:
        ShariaFilter(SHARIA_FILE).sync_legacy_compat(LEGACY_HALAL_FILE)
    except Exception as exc:
        audit('legacy_compat_sync_failed', severity='ERROR', details={'error': str(exc)})
    return record


def write_screening_outcome(request_id: str, base: str, pair: str, report: dict, *,
                            validated: bool, error: str = '', meta: dict | None = None) -> dict:
    """Validate independently, then persist report/result/status bindings."""
    base = str(base).upper().strip()
    pair = str(pair).upper().strip()
    request_id = str(request_id).strip()
    if not base.isalnum() or pair != f'{base}/USDT':
        raise ValueError('screening base/pair binding is invalid')
    if not REQUEST_ID_RE.fullmatch(request_id):
        raise ValueError('screening request_id is invalid')
    requested_validated = bool(validated)
    validation_error = ''
    try:
        load_controller(SHARIA_CONTROLLER_FILE)
        validate_result(report, expected_base=base)
    except Exception as exc:
        validation_error = f'{type(exc).__name__}: {exc}'
        report = fail_closed_report(base, reason='bridge validation failed: ' + validation_error)
        validated = False
    else:
        validated = requested_validated
        if not validated and str(report.get('final_code')) in TRADE_ELIGIBLE_CODES:
            report = fail_closed_report(base, reason='caller did not establish validation')
    if validation_error:
        error = '; '.join(x for x in (str(error or ''), validation_error) if x)

    SHARIA_REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    SHARIA_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    report_name = f'{base}_{request_id}.json'
    report_path = SHARIA_REPORTS_DIR / report_name
    atomic_write_json(report_path, report)
    report_sha = hashlib.sha256(report_path.read_bytes()).hexdigest()
    final_code = str(report['final_code'])
    completed_at = _now()
    payload = attach({
        'request_id': request_id, 'base': base, 'pair': pair,
        'final_code': final_code, 'validated': bool(validated),
        'direct_result': str(report.get('direct_result', 'NO TRADE')),
        'confidence_level': str(report.get('confidence_level', 'LOW')),
        'human_escalation_required': bool(report.get('human_escalation_required', False)),
        'next_rescreen_date': str(report.get('next_rescreen_date', '')),
        'report_file': report_name, 'report_sha256': report_sha,
        'completed_at': completed_at.isoformat(), 'error': str(error or ''),
        'meta': meta or {},
    }, purpose=RESULT_PURPOSE)
    ttl = env_int('SHARIA_RESULT_ENVELOPE_TTL_SECONDS', 7 * 86_400, 60, 30 * 86_400)
    signed = envelope.sign_envelope(
        producer=PRODUCER, purpose=envelope.BUS_SHARIA_RESULT,
        payload=payload, ttl_seconds=ttl)
    result_path = SHARIA_RESULTS_DIR / f'result_{request_id}.json'
    atomic_write_json(result_path, signed)
    record = update_status_projection(
        base, report, request_id=request_id, pair=pair, validated=bool(validated),
        report_file=report_name, report_sha256=report_sha, completed_at=completed_at)
    from services.common.retention import prune_files
    keep = env_int('SHARIA_ARCHIVE_MAX_FILES', 5000, 100, 100_000)
    retain_days = env_int('SHARIA_ARCHIVE_RETENTION_DAYS', 90, 7, 365)
    retain_seconds = retain_days * 86_400
    prune_files(SHARIA_REPORTS_DIR, '*.json', max_files=keep,
                max_age_seconds=retain_seconds)
    prune_files(SHARIA_RESULTS_DIR, '*.json', max_files=keep,
                max_age_seconds=retain_seconds)
    audit('sharia_screening_recorded', details={
        'request_id': request_id, 'base': base, 'final_code': final_code,
        'validated': bool(validated), 'error': str(error or '')[:200]})
    return {'payload': payload, 'record': record, 'result_path': str(result_path)}


def ensure_status_file_exists():
    """Replace missing/legacy plaintext state with one attested deny record."""
    try:
        gate = ShariaFilter(SHARIA_FILE)
        if any(gate.is_record_verified(base) for base in gate.records):
            return
    except Exception:
        pass
    stamp = _now().strftime('%Y%m%d')
    write_screening_outcome(
        f'bootstrap-BNB-{stamp}', 'BNB', 'BNB/USDT',
        fail_closed_report('BNB', reason='first-boot fail-closed bootstrap'),
        validated=False, error='bootstrap record; BNB is excluded by policy')
